DLS-10610 - Address compilation warnings
hmrc/cbcr pull request #240
Opened 2024-06-25 16:54 UTC by TomRafferty

Addresses various warnings through automated processes 
This shouldn't affect functionality.

2024-06-26 08:07 UTC, ruthdas03 approved these changes

2024-07-09 13:46 UTC, LAJW requested changes

2024-07-09 13:46 UTC, LAJW commented on app/uk/gov/hmrc/cbcr/Module.scala
> +  @unused
Don't use @unused

2024-07-09 14:38 UTC, LAJW commented on app/uk/gov/hmrc/cbcr/models/DocRefID.scala
> +  val dateFmt: DateTimeFormatter = DateTimeFormatter.ofPattern("yyyyMMdd'T'HHmmss")
There's still one left. This one almost definitely can be deleted if it's not used.

2024-07-09 14:39 UTC, LAJW approved these changes

2024-07-19 10:00 UTC, LAJW approved these changes

2024-07-19 11:01 UTC, merged